output: docs
clean: true
objc: true
umbrella_header: SteamController/SteamController.h
framework_root: .
sdk: iphonesimulator
author: Jesús A. Álvarez
author_url: https://github.com/zydeco
module: SteamController
github_url: https://github.com/zydeco/SteamController
github_file_prefix: https://github.com/zydeco/SteamController/tree/master
theme: fullwidth
